### PR TITLE
using https instead of ssh for cloning the repository

### PR DESCRIPTION
**Pull request by truatpasteurdotfr**
nitpicking the first steps as I am installing ;P

### CODE REVIEW

**Comment by jamaliki** [comment]
Looks great, thank you for the Dockerfile. Did you get things to install? Is the PR ready for a merge?

**Comment by truatpasteurdotfr** [comment]
docker is building fine , I am using docker as build system, as I am using singularity for runtime ;P

**Comment by jamaliki** [comment]
Great! Well, PR approved thank you very much. Are you done with it, shall I merge?

**Comment by truatpasteurdotfr** [comment]
I have uploaded 2 singularity recipes, one using the docker artefact produced by the github CI, and the other building from scratch as the Dockerfile is doing. Both versions are working for me.

**Comment by truatpasteurdotfr** [comment]
PR good to merge, imho.

**Comment by jamaliki** [comment]
Tyvm!

**Pull request merged**
